### PR TITLE
Change forecast api url to the new dark sky api

### PR DESCRIPTION
**Pull request by Myolnir**

### CODE REVIEW

**Comment by joosep-wm** [comment]
Do you know when the api.forecast.io domain will be shut down?

**Comment by Myolnir** [comment]
Hi, I just know they sent an email to a colleague of my company saying that the url of the api will change, for now both urls are working but they recommend that we change the url to the new one asap.

**Comment by joosep-wm** [comment]
@dvdme can you comment on this?

**Comment by jamesdesmond** [comment]
Are there any updates on this PR?

**Comment by dvdme** [comment]
Working on it. But the old URL will still work.

Em 06/10/2016 22:20, "James Desmond" <notifications@github.com> escreveu:

**Comment by amuelas** [comment]
Sure!, but I created the PR because forecast.io recommends change to the new url ASAP.

**Comment by dvdme** [comment]
Well, that is true. I will update it today or this weekend.

A sex, 7/10/2016, 08:45, Angel <notifications@github.com> escreveu:

Sure!, but I created the PR because forecast.io recommends change to the
new url ASAP.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/dvdme/forecastio-lib-java/pull/27#issuecomment-252174560>,
or mute the thread

**Comment by dvdme** [comment]
Merged

**Comment by joosep-wm** [comment]
Are there any plans to release this change as a new version in maven?

Would be nice to get the dependency from Maven, instead of building it myself and deploying manually with the application.

**Comment by dvdme** [comment]
Yes, I have not done it yet because I lost my maven keys.

I'll try to do it this week.

A ter, 1/11/2016, 16:26, Joosep Simm <notifications@github.com> escreveu:

**Comment by joosep-wm** [comment]
Nice!
Looking forward to it.

**Comment by joosep-wm** [comment]
Hey, how are you doing with the new version to maven?

**Comment by dvdme** [comment]
Version on maven is now updated.

**Pull request merged**
